title: Interview Essentials
email: mike.pan@wework.com
description: >- # this means to ignore newlines until "baseurl:"
  Interview Essentials
baseurl: /interview-essentials
url: https://mpan-wework.github.io
permalink: /posts/:year/:month/:day/:title
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme
remote_theme: mpan-wework/jekyll-theme-dummy
highlighter: rouge

include:
  - _redirects
exclude:
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - docker-compose.yml
  - Dockerfile
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
timezone: Asia/Shanghai
host: '0.0.0.0'
defaults:
  - scope:
      type: posts
      path: ''
    values:
      layout: post
      author: mpan_wework
      sitemap: true

feed:
  path: feed.xml
jekyll-mentions:
  base_url: https://github.com
